// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"work-management-app/infrastructure"
	"work-management-app/infrastructure/repository"
	"work-management-app/presentation/controller"
	"work-management-app/usecase"
)

// Injectors from wire.go:

// InitHistoryController HistoryControllerのインスタンスを初期化
//
//	Controllerが一番先頭の呼び出し関数のため
func InitHistoryController() (controller.HistoryController, error) {
	db, err := infrastructure.InitDB()
	if err != nil {
		return nil, err
	}
	historyRepository := repository.NewHistoryRepository(db)
	historyUsecase := usecase.NewHistoryUsecase(historyRepository)
	historyController := controller.NewHistoryController(historyUsecase)
	return historyController, nil
}

// InitActivityController InitActivityControllerのインスタンス初期化
func InitActivityController() (controller.ActivityController, error) {
	db, err := infrastructure.InitDB()
	if err != nil {
		return nil, err
	}
	activityRepository := repository.NewActivityRepository(db)
	activityUsecase := usecase.NewActivityUsecase(activityRepository)
	activityController := controller.NewActivityController(activityUsecase)
	return activityController, nil
}

// wire.go:

// HistoryControllerの依存関係
var historySuperSet = wire.NewSet(infrastructure.InitDB, repository.NewHistoryRepository, usecase.NewHistoryUsecase, controller.NewHistoryController)

// ActivityController周りの依存関係
var activitySuperSet = wire.NewSet(infrastructure.InitDB, repository.NewActivityRepository, usecase.NewActivityUsecase, controller.NewActivityController)
