// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"work-management-app/application/usecase"
	"work-management-app/domain/service"
	"work-management-app/infrastructure/database"
	"work-management-app/infrastructure/database/repository"
	"work-management-app/presentation/controller"
)

// Injectors from wire.go:

func InitializeControllers() (*ControllersSet, error) {
	db, err := database.InitDB()
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	activityRepository := repository.NewActivityRepository(db)
	transaction := repository.NewTransaction(db)
	userUsecase := usecase.NewUserUsecase(userRepository, activityRepository, transaction)
	userController := controller.NewUserController(userUsecase)
	historyRepository := repository.NewHistoryRepository(db)
	historyDomainService := service.NewHistoryDomainService()
	historyUsecase := usecase.NewHistoryUsecase(historyRepository, userRepository, historyDomainService)
	historyController := controller.NewHistoryController(historyUsecase)
	activityDomainService := service.NewActivityDomainService(activityRepository, historyRepository)
	activityUsecase := usecase.NewActivityUsecase(activityRepository, userRepository, activityDomainService, transaction)
	activityController := controller.NewActivityController(activityUsecase)
	controllersSet := &ControllersSet{
		UserController:     userController,
		HistoryController:  historyController,
		ActivityController: activityController,
	}
	return controllersSet, nil
}

// wire.go:

// infrastructure
var infrastructureSet = wire.NewSet(database.InitDB)

// domainService
var domainServiceSet = wire.NewSet(service.NewActivityDomainService, service.NewHistoryDomainService)

// repository
var repositorySet = wire.NewSet(repository.NewActivityRepository, repository.NewHistoryRepository, repository.NewUserRepository, repository.NewTransaction)

// application
var usecaseSet = wire.NewSet(usecase.NewActivityUsecase, usecase.NewHistoryUsecase, usecase.NewUserUsecase)

// controller
var controllerSet = wire.NewSet(controller.NewActivityController, controller.NewHistoryController, controller.NewUserController)

type ControllersSet struct {
	UserController     controller.UserController
	HistoryController  controller.HistoryController
	ActivityController controller.ActivityController
}
