// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"work-management-app/infrastructure"
	"work-management-app/infrastructure/repository"
	"work-management-app/presentation/controller"
	"work-management-app/usecase"
)

// Injectors from wire.go:

func InitializeControllers() (*ControllersSet, error) {
	db, err := infrastructure.InitDB()
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	activityRepository := repository.NewActivityRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository, activityRepository)
	userController := controller.NewUserController(userUsecase)
	historyRepository := repository.NewHistoryRepository(db)
	historyUsecase := usecase.NewHistoryUsecase(historyRepository, userRepository)
	historyController := controller.NewHistoryController(historyUsecase)
	activityUsecase := usecase.NewActivityUsecase(activityRepository, userRepository, historyRepository)
	activityController := controller.NewActivityController(activityUsecase)
	controllersSet := &ControllersSet{
		UserController:     userController,
		HistoryController:  historyController,
		ActivityController: activityController,
	}
	return controllersSet, nil
}

// wire.go:

// infrastructure
var infrastructureSet = wire.NewSet(infrastructure.InitDB)

// repository
var repositorySet = wire.NewSet(repository.NewActivityRepository, repository.NewHistoryRepository, repository.NewUserRepository)

// usecase
var usecaseSet = wire.NewSet(usecase.NewActivityUsecase, usecase.NewHistoryUsecase, usecase.NewUserUsecase)

// controller
var controllerSet = wire.NewSet(controller.NewActivityController, controller.NewHistoryController, controller.NewUserController)

type ControllersSet struct {
	UserController     controller.UserController
	HistoryController  controller.HistoryController
	ActivityController controller.ActivityController
}
